Global:
  debug: false
  use_gpu: true
  epoch_num: 1200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/castrated/dml_mul_b7_lr0.005_castrated/
  save_epoch_step: 1200
  eval_batch_step:
  - 0
  - 400
  load_static_weights: false
  cal_metric_during_train: false
  pretrained_model: null
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_en/img_10.jpg
  save_res_path: ./output/det_db/predicts_db.txt
  teacher_pretrained_model: ./pretrain_model/ch_ppocr_server_v2.0_det_train/best_accuracy
  student_pretrained_model: ./pretrain_model/MobileNetV3_large_x0_5_pretrained
  distributed: true
Architecture:
  model_type: det
  algorithm: DB
NetWorks:
  Student:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: MobileNetV3
      scale: 0.5
      model_name: large
      disable_se: true
    Neck:
      name: DBFPN
      out_channels: 96
    Head:
      name: DBHead
      k: 50
  Student2:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: MobileNetV3
      scale: 0.5
      model_name: large
      disable_se: true
    Neck:
      name: DBFPN
      out_channels: 96
    Head:
      name: DBHead
      k: 50
  Teacher:
    model_type: det
    algorithm: DB
    Transform: null
    Backbone:
      name: ResNet
      layers: 18
    Neck:
      name: DBFPN
      out_channels: 256
    Head:
      name: DBHead
      k: 50
Loss:
  name: DMLLossV2
  balance_loss: true
  main_loss_type: DiceLoss
  alpha: 5
  beta: 10
  ohem_ratio: 3
  dbloss_ratio: 1
  dmlloss_ratio: 1
  feature_loss: false
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.005
    warmup_epoch: 2
  regularizer:
    name: L2
    factor: 1.0e-05
PostProcess:
  name: DBPostProcess
  thresh: 0.3
  box_thresh: 0.6
  max_candidates: 1000
  unclip_ratio: 1.5
Metric:
  name: DetMetric
  main_indicator: hmean
Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../chinese/
    label_file_list:
    - ../chinese/label_train_all_f4_part2.txt
    - ../chinese/label_train_all_f4_part3.txt
    - ../chinese/label_train_all_f4_part4.txt
    - ../chinese/label_train_all_f4_part5.txt
    ratio_list:
    - 0.4
    - 0.2
    - 0.2
    - 0.4
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - IaaAugment:
        augmenter_args:
        - type: Fliplr
          args:
            p: 0.5
        - type: Affine
          args:
            rotate:
            - -10
            - 10
        - type: Resize
          args:
            size:
            - 0.5
            - 3
    - EastRandomCropData:
        size:
        - 960
        - 960
        max_tries: 50
        keep_ratio: true
    - MakeBorderMap:
        shrink_ratio: 0.4
        thresh_min: 0.3
        thresh_max: 0.7
    - MakeShrinkMap:
        shrink_ratio: 0.4
        min_text_size: 8
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - threshold_map
        - threshold_mask
        - shrink_map
        - shrink_mask
  loader:
    shuffle: true
    drop_last: false
    batch_size_per_card: 16
    num_workers: 4
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../chinese/test_set/
    label_file_list:
    - ../chinese/test_set/system_test_set_label_list_200.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - DetLabelEncode: null
    - DetResizeForTest: null
    - NormalizeImage:
        scale: 1./255.
        mean:
        - 0.485
        - 0.456
        - 0.406
        std:
        - 0.229
        - 0.224
        - 0.225
        order: hwc
    - ToCHWImage: null
    - KeepKeys:
        keep_keys:
        - image
        - shape
        - polys
        - ignore_tags
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1
    num_workers: 1
    use_shared_memory: false
